[package]
name = "ffactor"
version = "0.1.3"
edition = "2021"
description = "A very minimal number theory utilities"
license = "MIT"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
prettytable-rs = "^0.10"
